server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: ${POSTGRES_USER:shopflow}
    password: ${POSTGRES_PASSWORD:shopflow}
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
