eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # ← Использовать IP вместо hostname

server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: ${POSTGRES_USER:shopflow}
    password: ${POSTGRES_PASSWORD:shopflow}
  jpa:
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
