spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: ${POSTGRES_USER:shopflow}
    password: ${POSTGRES_PASSWORD:shopflow}
  jpa:
    show-sql: true
    open-in-view: false
  kafka:
    consumer:
      group-id: payment-service-group
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
